version: '3.1'
services:
  delivery-system:
    container_name: c_delivery-system
    image: delivery-system
    ports:
      - 3000:3000
    networks:
      - delivery-system
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: delivery-system
    ports:
      - 27017:27017
    networks:
      - delivery-system
networks:
  delivery-system: