// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Berkay Dogukan Urhan",
            "url": "https://www.linkedin.com/in/berkay-dogukan-urhan/",
            "email": "b.dogukanurhan@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "If package or sacks in correct delivery point, change status to unloaded. If not, set status to loaded.\nBranch Point can only receive packages, Distribution Point can receive everything, Transfer Point can receive only sacks and packages in sacks",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Post request for handle delivery status",
                "parameters": [
                    {
                        "description": "Request struct",
                        "name": "Routes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeliverDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeliverDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Delivery": {
            "type": "object",
            "properties": {
                "barcode": {
                    "type": "string"
                }
            }
        },
        "domain.Route": {
            "type": "object",
            "properties": {
                "deliveries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Delivery"
                    }
                },
                "deliveryPoint": {
                    "type": "integer"
                }
            }
        },
        "dto.DeliverDTO": {
            "type": "object",
            "properties": {
                "route": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Route"
                    }
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Delivery System Fleet Management Case Project",
	Description:      "This project can handle delivery system for Branch, Distribution and Transfer centers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
